# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spreadsheets.Cell'),
        ),
    ]
