# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-08 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheets', '0003_auto_20190103_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ('column', 'row'), 'verbose_name': 'Cell', 'verbose_name_plural': 'Cells'},
        ),
        migrations.AlterField(
            model_name='spreadsheet',
            name='file',
            field=models.FileField(upload_to='spreadsheets'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='company_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='spreadsheets.Cell'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='email',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='spreadsheets.Cell'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='first_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_name', to='spreadsheets.Cell'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='last_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_name', to='spreadsheets.Cell'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='snippet_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_1', to='spreadsheets.Cell'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='snippet_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_2', to='spreadsheets.Cell'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='snippet_3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_3', to='spreadsheets.Cell'),
        ),
    ]
