# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-02 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheets', '0004_auto_20190108_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ('row', 'column'), 'verbose_name': 'Cell', 'verbose_name_plural': 'Cells'},
        ),
    ]
