services:
  - type: web
    name: outbound-app
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn mailer.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: REDIS_URL
        value: redis://red-cto1115umphs73casv40:6379
      - key: DATABASE_URL
        fromDatabase:
          name: outbound-db
          property: connectionString

  - type: redis
    name: outbound-redis
    ipAllowList: []
    plan: free

databases:
  - name: outbound-db
    databaseName: outbound
    user: outbound 