# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 17:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_messages_counter', models.PositiveSmallIntegerField(default=0)),
                ('current_message_index', models.PositiveSmallIntegerField(default=0)),
                ('daily_limit', models.PositiveSmallIntegerField(default=100, help_text='Daily limit of outbound messages.')),
                ('interval', models.PositiveSmallIntegerField(default=3, help_text='Interval between campaigns (in days).')),
                ('is_active', models.BooleanField(default=True)),
                ('is_active_on_sunday', models.BooleanField(default=True)),
                ('sunday_start_time', models.CharField(blank=True, choices=[('(0, 0)', '12 AM'), ('(1, 0)', '01 AM'), ('(2, 0)', '02 AM'), ('(3, 0)', '03 AM'), ('(4, 0)', '04 AM'), ('(5, 0)', '05 AM'), ('(6, 0)', '06 AM'), ('(7, 0)', '07 AM'), ('(8, 0)', '08 AM'), ('(9, 0)', '09 AM'), ('(10, 0)', '10 AM'), ('(11, 0)', '11 AM'), ('(12, 0)', '12 PM'), ('(13, 0)', '01 PM'), ('(14, 0)', '02 PM'), ('(15, 0)', '03 PM'), ('(16, 0)', '04 PM'), ('(17, 0)', '05 PM'), ('(18, 0)', '06 PM'), ('(19, 0)', '07 PM'), ('(20, 0)', '08 PM'), ('(21, 0)', '09 PM'), ('(22, 0)', '10 PM'), ('(23, 0)', '11 PM')], max_length=255)),
                ('is_active_on_monday', models.BooleanField(default=True)),
                ('monday_start_time', models.CharField(blank=True, choices=[('(0, 0)', '12 AM'), ('(1, 0)', '01 AM'), ('(2, 0)', '02 AM'), ('(3, 0)', '03 AM'), ('(4, 0)', '04 AM'), ('(5, 0)', '05 AM'), ('(6, 0)', '06 AM'), ('(7, 0)', '07 AM'), ('(8, 0)', '08 AM'), ('(9, 0)', '09 AM'), ('(10, 0)', '10 AM'), ('(11, 0)', '11 AM'), ('(12, 0)', '12 PM'), ('(13, 0)', '01 PM'), ('(14, 0)', '02 PM'), ('(15, 0)', '03 PM'), ('(16, 0)', '04 PM'), ('(17, 0)', '05 PM'), ('(18, 0)', '06 PM'), ('(19, 0)', '07 PM'), ('(20, 0)', '08 PM'), ('(21, 0)', '09 PM'), ('(22, 0)', '10 PM'), ('(23, 0)', '11 PM')], max_length=255)),
                ('is_active_on_tuesday', models.BooleanField(default=True)),
                ('tuesday_start_time', models.CharField(blank=True, choices=[('(0, 0)', '12 AM'), ('(1, 0)', '01 AM'), ('(2, 0)', '02 AM'), ('(3, 0)', '03 AM'), ('(4, 0)', '04 AM'), ('(5, 0)', '05 AM'), ('(6, 0)', '06 AM'), ('(7, 0)', '07 AM'), ('(8, 0)', '08 AM'), ('(9, 0)', '09 AM'), ('(10, 0)', '10 AM'), ('(11, 0)', '11 AM'), ('(12, 0)', '12 PM'), ('(13, 0)', '01 PM'), ('(14, 0)', '02 PM'), ('(15, 0)', '03 PM'), ('(16, 0)', '04 PM'), ('(17, 0)', '05 PM'), ('(18, 0)', '06 PM'), ('(19, 0)', '07 PM'), ('(20, 0)', '08 PM'), ('(21, 0)', '09 PM'), ('(22, 0)', '10 PM'), ('(23, 0)', '11 PM')], max_length=255)),
                ('is_active_on_wednesday', models.BooleanField(default=True)),
                ('wednesday_start_time', models.CharField(blank=True, choices=[('(0, 0)', '12 AM'), ('(1, 0)', '01 AM'), ('(2, 0)', '02 AM'), ('(3, 0)', '03 AM'), ('(4, 0)', '04 AM'), ('(5, 0)', '05 AM'), ('(6, 0)', '06 AM'), ('(7, 0)', '07 AM'), ('(8, 0)', '08 AM'), ('(9, 0)', '09 AM'), ('(10, 0)', '10 AM'), ('(11, 0)', '11 AM'), ('(12, 0)', '12 PM'), ('(13, 0)', '01 PM'), ('(14, 0)', '02 PM'), ('(15, 0)', '03 PM'), ('(16, 0)', '04 PM'), ('(17, 0)', '05 PM'), ('(18, 0)', '06 PM'), ('(19, 0)', '07 PM'), ('(20, 0)', '08 PM'), ('(21, 0)', '09 PM'), ('(22, 0)', '10 PM'), ('(23, 0)', '11 PM')], max_length=255)),
                ('is_active_on_thursday', models.BooleanField(default=True)),
                ('thursday_start_time', models.CharField(blank=True, choices=[('(0, 0)', '12 AM'), ('(1, 0)', '01 AM'), ('(2, 0)', '02 AM'), ('(3, 0)', '03 AM'), ('(4, 0)', '04 AM'), ('(5, 0)', '05 AM'), ('(6, 0)', '06 AM'), ('(7, 0)', '07 AM'), ('(8, 0)', '08 AM'), ('(9, 0)', '09 AM'), ('(10, 0)', '10 AM'), ('(11, 0)', '11 AM'), ('(12, 0)', '12 PM'), ('(13, 0)', '01 PM'), ('(14, 0)', '02 PM'), ('(15, 0)', '03 PM'), ('(16, 0)', '04 PM'), ('(17, 0)', '05 PM'), ('(18, 0)', '06 PM'), ('(19, 0)', '07 PM'), ('(20, 0)', '08 PM'), ('(21, 0)', '09 PM'), ('(22, 0)', '10 PM'), ('(23, 0)', '11 PM')], max_length=255)),
                ('is_active_on_friday', models.BooleanField(default=True)),
                ('friday_start_time', models.CharField(blank=True, choices=[('(0, 0)', '12 AM'), ('(1, 0)', '01 AM'), ('(2, 0)', '02 AM'), ('(3, 0)', '03 AM'), ('(4, 0)', '04 AM'), ('(5, 0)', '05 AM'), ('(6, 0)', '06 AM'), ('(7, 0)', '07 AM'), ('(8, 0)', '08 AM'), ('(9, 0)', '09 AM'), ('(10, 0)', '10 AM'), ('(11, 0)', '11 AM'), ('(12, 0)', '12 PM'), ('(13, 0)', '01 PM'), ('(14, 0)', '02 PM'), ('(15, 0)', '03 PM'), ('(16, 0)', '04 PM'), ('(17, 0)', '05 PM'), ('(18, 0)', '06 PM'), ('(19, 0)', '07 PM'), ('(20, 0)', '08 PM'), ('(21, 0)', '09 PM'), ('(22, 0)', '10 PM'), ('(23, 0)', '11 PM')], max_length=255)),
                ('is_active_on_saturday', models.BooleanField(default=True)),
                ('saturday_start_time', models.CharField(blank=True, choices=[('(0, 0)', '12 AM'), ('(1, 0)', '01 AM'), ('(2, 0)', '02 AM'), ('(3, 0)', '03 AM'), ('(4, 0)', '04 AM'), ('(5, 0)', '05 AM'), ('(6, 0)', '06 AM'), ('(7, 0)', '07 AM'), ('(8, 0)', '08 AM'), ('(9, 0)', '09 AM'), ('(10, 0)', '10 AM'), ('(11, 0)', '11 AM'), ('(12, 0)', '12 PM'), ('(13, 0)', '01 PM'), ('(14, 0)', '02 PM'), ('(15, 0)', '03 PM'), ('(16, 0)', '04 PM'), ('(17, 0)', '05 PM'), ('(18, 0)', '06 PM'), ('(19, 0)', '07 PM'), ('(20, 0)', '08 PM'), ('(21, 0)', '09 PM'), ('(22, 0)', '10 PM'), ('(23, 0)', '11 PM')], max_length=255)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='Parameter will be used in "From" email section.', max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('fail_silently', models.BooleanField(default=False)),
                ('host', models.CharField(default='smtp.gmail.com', max_length=30)),
                ('port', models.PositiveSmallIntegerField(default=587)),
                ('host_user', models.CharField(help_text='Your email address such as example@gmail.com.', max_length=255)),
                ('host_password', models.CharField(help_text='Your password for email address account.', max_length=255)),
            ],
            options={
                'verbose_name': 'Mailbox',
                'verbose_name_plural': 'Mailboxes',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='You can use tags in subject field {{ First Name }},\n                         {{ Last Name }}" and {{ Company Name }}, they are\n                         <u><strong> case-sensitive</strong></u>.\n                         <br><strong>Example of usage:</strong>\n                         Hello, {{ First Name}} {{ Last Name }},\n                         here will be subject for you.\n                         Tags: {{ First Name }}, {{ Last Name }}\n                         {{ Company Name }} {{ Snippet 1 }} {{ Snippet 2 }} {{ Snippet 3 }}', max_length=255)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(help_text='You can use tags in message field {{ First Name }},\n                         {{ Last Name }} and {{ Company Name }}, they are\n                         <u><strong> case-sensitive</strong></u>.\n                         <br><strong>Example of usage:</strong>\n                         Hello, {{ First Name}} {{ Last Name }},\n                         here will be text message for you.\n                         Tags: {{ First Name }}, {{ Last Name }}\n                         {{ Company Name }} {{ Snippet 1 }} {{ Snippet 2 }} {{ Snippet 3 }}')),
                ('opened', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('replied', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('total_sent', models.PositiveSmallIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('snippet_1', models.CharField(blank=True, max_length=255)),
                ('snippet_2', models.CharField(blank=True, max_length=255)),
                ('snippet_3', models.CharField(blank=True, max_length=255)),
                ('bounced', models.BooleanField(default=False)),
                ('opened_message', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('next_processed_time', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaigns.Campaign')),
            ],
            options={
                'verbose_name': 'Recipient',
                'verbose_name_plural': 'Recipients',
            },
        ),
    ]
