# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('spreadsheets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='spreadsheet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipients', to='spreadsheets.Spreadsheet'),
        ),
        migrations.AddField(
            model_name='message',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campaigns.Campaign'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='campaign',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='campaigns.Campaign'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
