# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 12:31
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20190103_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='full_name',
            field=models.CharField(blank=True, help_text='Parameter will be used as "from" email address.', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(help_text='You can use tags in subject field {{ First Name }},\n                               {{ Last Name }}" and {{ Company Name }}, they are\n                               <u><strong> case-sensitive</strong></u>.\n                               <br><strong>Example of usage:</strong>\n                               Hello, {{ First Name}} {{ Last Name }},\n                               here will be subject for you.\n                               Tags: {{ First Name }}, {{ Last Name }}\n                               {{ Company Name }} {{ Snippet 1 }} {{ Snippet 2 }} {{ Snippet 3 }}', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='You can use tags in message field {{ First Name }},\n                            {{ Last Name }} and {{ Company Name }}, they are\n                            <u><strong> case-sensitive</strong></u>.\n                            <br><strong>Example of usage:</strong>\n                            Hello, {{ First Name}} {{ Last Name }},\n                            here will be text message for you.\n                            Tags: {{ First Name }}, {{ Last Name }}\n                            {{ Company Name }} {{ Snippet 1 }} {{ Snippet 2 }} {{ Snippet 3 }}'),
        ),
    ]
