# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20190103_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='spreadsheet',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='spreadsheets.Spreadsheet'),
        ),
    ]
