# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-08 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20190103_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbox',
            name='campaign',
        ),
        migrations.AddField(
            model_name='campaign',
            name='mailbox',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaigns', to='campaigns.Mailbox'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='full_name',
            field=models.CharField(blank=True, help_text='Parameter will be used as "from" name. Example: Mr. Black.', max_length=255),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='host_user',
            field=models.CharField(help_text='Your email address. Example: example@gmail.com.', max_length=255),
        ),
    ]
