# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-12 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20190108_1531'),
        ('campaigns', '0009_auto_20190108_1704'),
    ]

    operations = [
    ]
