# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-02 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_merge_20190112_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='host_user',
            field=models.CharField(help_text='Your email address. Example: example@gmail.com.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='spreadsheet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='spreadsheets.Spreadsheet'),
        ),
    ]
